try git pull again 2

diff --git a/.github/workflows/docs_gh_pages.yml b/.github/workflows/docs_gh_pages.yml
--- a/.github/workflows/docs_gh_pages.yml
+++ b/.github/workflows/docs_gh_pages.yml
@@ -12,10 +12,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v1
-#       Standard drop-in approach that should work for most people.
-#      - uses: ammaraskar/sphinx-action@master
-#        with:
-#          docs-folder: "docs/source/"
+
       - uses: ammaraskar/sphinx-action@master
         with:
           docs-folder: "docs/"
@@ -29,18 +26,35 @@ jobs:
       # ===============================
       - name: Commit documentation changes
         run: |
-          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
-          cp -r docs/build/html/* gh-pages/
+          git clone https://github.com/RedVoxInc/Skyfall.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
           cd gh-pages
-          touch .nojekyll
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add .
           git commit -m "Update documentation" -a || true
           # The above command will fail if no changes were present, so we ignore
-          # that.
-      - name: Git pull
-        run: git pull origin gh-pages
+          # the return code.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Commit documentation changes
+#        run: |
+#          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
+#          cp -r docs/build/html/* gh-pages/
+#          cd gh-pages
+#          touch .nojekyll
+#          git config --local user.email "action@github.com"
+#          git config --local user.name "GitHub Action"
+#          git add .
+#          git commit -m "Update documentation" -a || true
+#          # The above command will fail if no changes were present, so we ignore
+#          # that.
+#      - name: Git pull
+#        run: git pull origin gh-pages
 
       - name: Push changes
         uses: ad-m/github-push-action@master
